# Generated by Django 6.0.4 on 2026-04-18 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="attendance_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="attendance_access_granted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="attendance_access_granted_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="employee_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="employee_access_granted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="employee_access_granted_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="invoice_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="invoice_access_granted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="invoice_access_granted_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="masters_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="masters_access_granted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="masters_access_granted_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="notice_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="notice_access_granted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="notice_access_granted_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="org",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.CreateModel(
            name="OrgMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("manager", "Manager"), ("employee", "Employee")],
                        default="employee",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Marks the user's primary org. At most one membership per user carries this.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_access", models.BooleanField(default=False)),
                ("notice_access", models.BooleanField(default=False)),
                ("masters_access", models.BooleanField(default=False)),
                ("attendance_access", models.BooleanField(default=False)),
                ("employee_access", models.BooleanField(default=False)),
                ("invoice_access_granted_at", models.DateTimeField(blank=True, null=True)),
                ("notice_access_granted_at", models.DateTimeField(blank=True, null=True)),
                ("masters_access_granted_at", models.DateTimeField(blank=True, null=True)),
                ("attendance_access_granted_at", models.DateTimeField(blank=True, null=True)),
                ("employee_access_granted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attendance_access_granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_access_granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice_access_granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "masters_access_granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notice_access_granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="users.org"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "org membership",
                "verbose_name_plural": "org memberships",
                "db_table": "users_orgmembership",
                "ordering": ["-is_default", "org__name"],
                "unique_together": {("user", "org")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="orgs",
            field=models.ManyToManyField(
                blank=True,
                related_name="members",
                through="users.OrgMembership",
                through_fields=("user", "org"),
                to="users.org",
            ),
        ),
    ]
