# Generated by Django 6.0.4 on 2026-06-12 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_orgmembership_exclude_op_standup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_code', models.CharField(max_length=64)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_rights', to='users.orgmembership')),
            ],
            options={
                'db_table': 'users_menuright',
                'ordering': ['membership_id', 'menu_code'],
                'unique_together': {('membership', 'menu_code')},
            },
        ),
    ]
