# Generated by Django 6.0.4 on 2026-07-05 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_backfill_menu_rights"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgmembership",
            name="costing_access",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="orgmembership",
            name="costing_access_granted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orgmembership",
            name="costing_access_granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
