# Generated by Django 6.0.4 on 2026-04-17 03:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("masters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaceChecklist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("fy", models.CharField(db_index=True, max_length=8)),
                ("week_number", models.IntegerField()),
                ("item_number", models.IntegerField()),
                ("action_item", models.TextField()),
                ("done", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "pace checklist item",
                "verbose_name_plural": "pace checklist items",
                "ordering": ["fy", "week_number", "item_number"],
            },
        ),
        migrations.CreateModel(
            name="PaceGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[("Result", "Result"), ("Skill", "Skill"), ("Attitude", "Attitude")],
                        default="Skill",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Achieved", "Achieved"),
                            ("Needs Attention", "Needs Attention"),
                        ],
                        db_index=True,
                        default="Not Started",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("Critical", "Critical"), ("Development", "Development"), ("Stretch", "Stretch")],
                        default="Development",
                        max_length=20,
                    ),
                ),
                ("current_rating", models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ("target_rating", models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ("success_criteria", models.TextField(blank=True)),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("45 Days", "45 Days"),
                            ("Fortnightly", "Fortnightly"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("target", models.CharField(blank=True, default="", max_length=255)),
                ("tracking_method", models.TextField(blank=True)),
                ("learning_action", models.TextField(blank=True)),
                ("completion_by", models.DateField(blank=True, null=True)),
                (
                    "iceberg_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Skill", "Skill"),
                            ("Knowledge", "Knowledge"),
                            ("Self-Image", "Self-Image"),
                            ("Trait", "Trait"),
                            ("Motive", "Motive"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "focus_area",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Practice", "Practice"),
                            ("Build Habit", "Build Habit"),
                            ("Strengthen", "Strengthen"),
                            ("Deepen", "Deepen"),
                            ("Develop", "Develop"),
                            ("Sustain", "Sustain"),
                            ("Sustain & Model", "Sustain & Model"),
                            ("Sustain & Expand", "Sustain & Expand"),
                            ("Channel", "Channel"),
                            ("Channel into BD", "Channel into BD"),
                            ("Activate Intentionally", "Activate Intentionally"),
                            ("Build Urgently", "Build Urgently"),
                            ("Build Consistently", "Build Consistently"),
                            ("Strengthen Urgently", "Strengthen Urgently"),
                            ("Ignite", "Ignite"),
                            ("Ignite Immediately", "Ignite Immediately"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("daily_practice", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "pace goal",
                "verbose_name_plural": "pace goals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaceGoalReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("review_date", models.DateField()),
                ("previous_rating", models.IntegerField(default=0)),
                ("new_rating", models.IntegerField(default=0)),
                ("reviewer_name", models.CharField(blank=True, default="", max_length=150)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "pace goal review",
                "verbose_name_plural": "pace goal reviews",
                "ordering": ["-review_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaceMeeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[("Strategic", "Strategic"), ("Tactical", "Tactical"), ("Operational", "Operational")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(db_index=True)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="Scheduled",
                        max_length=20,
                    ),
                ),
                ("agenda", models.TextField(blank=True)),
                ("minutes", models.TextField(blank=True)),
                ("attendees", models.JSONField(blank=True, default=list)),
                ("action_items", models.JSONField(blank=True, default=list)),
                ("conducted_by", models.CharField(blank=True, default="", max_length=150)),
            ],
            options={
                "verbose_name": "pace meeting",
                "verbose_name_plural": "pace meetings",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="ClientClassification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("classification", models.CharField(blank=True, default="", max_length=5)),
                ("revenue_tier", models.CharField(blank=True, default="", max_length=10)),
                ("strategic_importance", models.CharField(blank=True, default="", max_length=20)),
                ("relationship_health", models.CharField(blank=True, default="", max_length=20)),
                ("growth_potential", models.CharField(blank=True, default="", max_length=10)),
                ("risk_level", models.CharField(blank=True, default="", max_length=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "client"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_classifications",
                        to="masters.master",
                    ),
                ),
            ],
            options={
                "verbose_name": "client classification",
                "verbose_name_plural": "client classifications",
                "ordering": ["client"],
            },
        ),
    ]
