# Generated by Django 5.2.13 on 2026-05-05 01:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pace', '0002_initial'),
        ('users', '0005_orgmembership_exclude_op_standup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalStandup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('standup_date', models.DateField(db_index=True)),
                ('breakthrough_type', models.CharField(blank=True, choices=[('Breakdown', 'Breakdown'), ('Breakthrough', 'Breakthrough')], default='', max_length=20)),
                ('priorities', models.TextField(blank=True)),
                ('collaboration_need', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], db_index=True, default='Pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_standups_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_standups_created', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_standups', to='users.org')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_standups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'operational standup',
                'verbose_name_plural': 'operational standups',
                'ordering': ['-standup_date', 'profile__full_name'],
                'indexes': [models.Index(fields=['org', 'standup_date'], name='op_standup_org_date_idx'), models.Index(fields=['org', 'status'], name='op_standup_org_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'profile', 'standup_date'), name='uniq_op_standup_org_profile_date')],
            },
        ),
    ]
