# Generated by Django 6.0.4 on 2026-05-21 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pace', '0004_operationalstandup_reviewed'),
        ('users', '0005_orgmembership_exclude_op_standup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalStandupApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], db_index=True, default='Pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op_standup_approvals_approved', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_standup_approvals', to='users.org')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op_standup_approvals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('standup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='pace.operationalstandup')),
            ],
            options={
                'verbose_name': 'operational standup approval',
                'verbose_name_plural': 'operational standup approvals',
                'indexes': [models.Index(fields=['org', 'status'], name='op_approval_org_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('standup', 'org'), name='uniq_op_approval_standup_org')],
            },
        ),
    ]
