# Generated by Django 5.2.13 on 2026-04-25 17:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_orgmembership_leads_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_session', models.CharField(choices=[('Full', 'Full'), ('First Half', 'First Half'), ('Second Half', 'Second Half')], default='Full', max_length=12)),
                ('to_session', models.CharField(choices=[('Full', 'Full'), ('First Half', 'First Half'), ('Second Half', 'Second Half')], default='Full', max_length=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], db_index=True, default='Pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('total_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_decisions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_created', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='users.org')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'leave request',
                'verbose_name_plural': 'leave requests',
                'ordering': ['-from_date', '-id'],
                'indexes': [models.Index(fields=['status', 'org'], name='leave_leave_status_721c7d_idx'), models.Index(fields=['user', 'from_date', 'to_date'], name='leave_leave_user_id_bd0400_idx')],
            },
        ),
    ]
