# Generated by Django 6.0.4 on 2026-04-17 03:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrowthPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("activity", models.TextField()),
                ("target_month", models.DateField(blank=True, null=True)),
                ("steps_taken", models.TextField(blank=True)),
                ("steps_to_take", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Under Progress", "Under Progress"),
                            ("Completed", "Completed"),
                            ("On Hold", "On Hold"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="Open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                        db_index=True,
                        default="Medium",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "growth plan",
                "verbose_name_plural": "growth plans",
                "ordering": ["target_month", "priority"],
            },
        ),
    ]
