import type { RestoreLogEntry } from "@/types";
import type { BackupPayload, BackupRestoreMode } from "@/types/api";

interface RestoreModalProps {
  restoreOpen: boolean;
  restoreMode: BackupRestoreMode;
  restoreData: BackupPayload | null;
  restoreFileName: string;
  restoring: boolean;
  restoreLog: RestoreLogEntry[];
  restoreDone: boolean;
  restoreRef: React.RefObject<HTMLInputElement | null>;
  onRestoreFile: (e: React.ChangeEvent<HTMLInputElement>) => void;
  onRestore: () => void;
  onClose: () => void;
  onModeChange: (mode: BackupRestoreMode) => void;
}

export default function RestoreModal({
  restoreOpen,
  restoreMode,
  restoreData,
  restoreFileName,
  restoring,
  restoreLog,
  restoreDone,
  restoreRef,
  onRestoreFile,
  onRestore,
  onClose,
  onModeChange,
}: RestoreModalProps) {
  if (!restoreOpen) return null;

  return (
    <div className="overlay" onClick={onClose}>
      <div
        className="modal"
        style={{ width: 580 }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="modal-head">
          <span className="modal-title">📥 Restore from Backup</span>
          <button
            className="modal-close"
            onClick={onClose}
            disabled={restoring}
          >
            ✕
          </button>
        </div>
        <div className="modal-body">
          {!restoreDone && (
            <>
              <div
                style={{
                  background: "#fef3c7",
                  border: "1px solid #fbbf24",
                  borderRadius: 8,
                  padding: "10px 14px",
                  marginBottom: 14,
                  fontSize: 12,
                  color: "#92400e",
                }}
              >
                ⚠️ <strong>Important:</strong> Only restore from a backup file
                generated by this tool. Incorrect files may corrupt data.
              </div>

              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "1fr 1fr",
                  gap: 10,
                  marginBottom: 14,
                }}
              >
                {(
                  [
                    {
                      value: "upsert",
                      icon: "✅",
                      title: "UPSERT (Safe)",
                      sub: "Adds new rows & updates existing ones by ID.\nNo data is deleted — safest option.",
                    },
                    {
                      value: "replace",
                      icon: "⚠️",
                      title: "REPLACE (Full Reset)",
                      sub: "Deletes ALL current data in each table first,\nthen inserts from backup. Cannot be undone.",
                    },
                  ] as const
                ).map((opt) => (
                  <label
                    key={opt.value}
                    style={{
                      display: "flex",
                      alignItems: "flex-start",
                      gap: 10,
                      padding: "12px 14px",
                      borderRadius: 8,
                      cursor: "pointer",
                      border: `2px solid ${restoreMode === opt.value ? "#2563eb" : "#e2e8f0"}`,
                      background:
                        restoreMode === opt.value ? "#eff6ff" : "#fff",
                      transition: "all .15s",
                    }}
                  >
                    <input
                      type="radio"
                      name="restoreMode"
                      value={opt.value}
                      checked={restoreMode === opt.value}
                      onChange={() => onModeChange(opt.value)}
                      style={{ marginTop: 3, accentColor: "#2563eb" }}
                    />
                    <div>
                      <div
                        style={{
                          fontSize: 13,
                          fontWeight: 700,
                          color:
                            restoreMode === opt.value ? "#2563eb" : "#1e293b",
                        }}
                      >
                        {opt.icon} {opt.title}
                      </div>
                      <div
                        style={{
                          fontSize: 11,
                          color: "#64748b",
                          marginTop: 2,
                          lineHeight: 1.5,
                          whiteSpace: "pre-line",
                        }}
                      >
                        {opt.sub}
                      </div>
                    </div>
                  </label>
                ))}
              </div>

              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 10,
                  marginBottom: 14,
                }}
              >
                <button
                  className="btn btn-secondary"
                  onClick={() => restoreRef.current?.click()}
                  style={{ whiteSpace: "nowrap" }}
                >
                  📂 Choose backup file
                </button>
                <input
                  ref={restoreRef}
                  type="file"
                  accept=".json"
                  style={{ display: "none" }}
                  onChange={onRestoreFile}
                />
                <span style={{ fontSize: 12, color: "#64748b" }}>
                  {restoreFileName
                    ? `✅ ${restoreFileName}`
                    : "Select a .json backup file"}
                </span>
              </div>

              {restoreData && (
                <div
                  style={{
                    background: "#f0fdf4",
                    border: "1px solid #86efac",
                    borderRadius: 8,
                    padding: "10px 14px",
                    marginBottom: 14,
                    fontSize: 12,
                  }}
                >
                  <div
                    style={{
                      fontWeight: 700,
                      color: "#15803d",
                      marginBottom: 6,
                    }}
                  >
                    📋 Backup File Info
                  </div>
                  <div style={{ color: "#166534" }}>
                    📅 Exported:{" "}
                    <strong>
                      {new Date(restoreData.generated_at).toLocaleString()}
                    </strong>
                  </div>
                  <div
                    style={{
                      marginTop: 6,
                      display: "flex",
                      flexWrap: "wrap",
                      gap: "4px 12px",
                    }}
                  >
                    {Object.entries(restoreData.counts).map(([t, count]) => (
                      <span key={t} style={{ fontSize: 11, color: "#475569" }}>
                        <strong>{t}</strong>: {count} rows
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {restoreLog.length > 0 && (
                <div
                  style={{
                    maxHeight: 180,
                    overflowY: "auto",
                    background: "#f8fafc",
                    border: "1px solid #e2e8f0",
                    borderRadius: 8,
                    padding: "10px 14px",
                    fontSize: 12,
                  }}
                >
                  {restoreLog.map((entry, i) => (
                    <div
                      key={i}
                      style={{ display: "flex", gap: 8, marginBottom: 3 }}
                    >
                      <span>
                        {entry.status === "ok"
                          ? "✅"
                          : entry.status === "error"
                            ? "❌"
                            : "⏭️"}
                      </span>
                      <span style={{ fontWeight: 700, minWidth: 160 }}>
                        {entry.table}
                      </span>
                      <span
                        style={{
                          color:
                            entry.status === "error" ? "#dc2626" : "#475569",
                        }}
                      >
                        {entry.msg}
                      </span>
                    </div>
                  ))}
                  {restoring && (
                    <div style={{ color: "#2563eb", marginTop: 4 }}>
                      ⏳ Restoring, please wait…
                    </div>
                  )}
                </div>
              )}
            </>
          )}

          {restoreDone && (
            <div>
              <div
                style={{ textAlign: "center", fontSize: 32, marginBottom: 8 }}
              >
                🎉
              </div>
              <div
                style={{
                  textAlign: "center",
                  fontWeight: 700,
                  color: "#15803d",
                  marginBottom: 14,
                  fontSize: 15,
                }}
              >
                Restore Complete!
              </div>
              <div
                style={{
                  maxHeight: 220,
                  overflowY: "auto",
                  background: "#f8fafc",
                  border: "1px solid #e2e8f0",
                  borderRadius: 8,
                  padding: "10px 14px",
                  fontSize: 12,
                }}
              >
                {restoreLog.map((entry, i) => (
                  <div
                    key={i}
                    style={{ display: "flex", gap: 8, marginBottom: 3 }}
                  >
                    <span>
                      {entry.status === "ok"
                        ? "✅"
                        : entry.status === "error"
                          ? "❌"
                          : "⏭️"}
                    </span>
                    <span style={{ fontWeight: 700, minWidth: 160 }}>
                      {entry.table}
                    </span>
                    <span
                      style={{
                        color: entry.status === "error" ? "#dc2626" : "#475569",
                      }}
                    >
                      {entry.msg}
                    </span>
                  </div>
                ))}
              </div>
              <div
                style={{
                  marginTop: 12,
                  fontSize: 12,
                  color: "#64748b",
                  textAlign: "center",
                }}
              >
                Please refresh the page to see the restored data.
              </div>
            </div>
          )}
        </div>

        <div className="modal-foot">
          <button
            className="btn btn-secondary"
            onClick={onClose}
            disabled={restoring}
          >
            {restoreDone ? "Close" : "Cancel"}
          </button>
          {!restoreDone && (
            <button
              className="btn btn-primary"
              onClick={() => {
                if (restoreMode === "replace") {
                  if (
                    !window.confirm(
                      `⚠️ REPLACE mode will permanently delete ALL current data in every table and replace it with the backup.\n\nAre you absolutely sure?`,
                    )
                  )
                    return;
                }
                onRestore();
              }}
              disabled={!restoreData || restoring}
              style={{
                background: restoreMode === "replace" ? "#dc2626" : "#2563eb",
              }}
            >
              {restoring
                ? "⏳ Restoring…"
                : restoreMode === "replace"
                  ? "⚠️ Replace & Restore"
                  : "📥 Restore Backup"}
            </button>
          )}
          {restoreDone && (
            <button
              className="btn btn-primary"
              onClick={() => window.location.reload()}
              style={{ background: "#16a34a" }}
            >
              🔄 Refresh Page
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
