# Generated by Django 6.0.4 on 2026-04-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField(blank=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "app setting",
                "verbose_name_plural": "app settings",
                "ordering": ["key"],
            },
        ),
    ]
