# Generated by Django 6.0.4 on 2026-07-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApkRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('remarks', models.TextField(blank=True, default='', help_text="What changed in this build — shown in the app's release table.")),
            ],
            options={
                'verbose_name': 'APK release',
                'verbose_name_plural': 'APK releases',
                'ordering': ['-created_at'],
            },
        ),
    ]
