# Generated by Django 6.0.4 on 2026-04-17 03:30

import uuid

from django.db import migrations, models

import core.filestore.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "chat member",
                "verbose_name_plural": "chat members",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("message", models.TextField(blank=True)),
                ("file", models.FileField(blank=True, null=True, upload_to=core.filestore.validators.chat_upload_to)),
                ("file_type", models.CharField(blank=True, default="", max_length=100)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "chat message",
                "verbose_name_plural": "chat messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("direct", "Direct"), ("group", "Group")],
                        db_index=True,
                        default="direct",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "chat room",
                "verbose_name_plural": "chat rooms",
            },
        ),
    ]
