# Generated by Django 6.0.4 on 2026-04-17 03:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("masters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "serial_no",
                    models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
                ),
                ("dispute_nature", models.TextField()),
                ("fy", models.CharField(blank=True, default="", max_length=10)),
                ("received_date", models.DateField(blank=True, null=True)),
                ("replied_date", models.DateField(blank=True, null=True)),
                ("next_target_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Replied", "Replied"),
                            ("Appealed", "Appealed"),
                            ("Completed", "Completed"),
                        ],
                        db_index=True,
                        default="Open",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "client"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_notices",
                        to="masters.master",
                    ),
                ),
            ],
            options={
                "verbose_name": "notice",
                "verbose_name_plural": "notices",
                "ordering": ["-created_at"],
            },
        ),
    ]
