# Generated by Django 6.0.4 on 2026-06-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
