# Generated by Django 6.0.4 on 2026-04-17 03:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Master",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("client", "Client"), ("category", "Category"), ("team", "Team")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(blank=True, default="", max_length=20)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "master",
                "verbose_name_plural": "masters",
                "ordering": ["type", "sort_order", "name"],
            },
        ),
    ]
