# Generated by Django 6.0.4 on 2026-04-18 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0002_initial"),
        ("users", "0002_remove_user_attendance_access_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="master",
            name="master_type_valid",
        ),
        migrations.AlterField(
            model_name="master",
            name="type",
            field=models.CharField(
                choices=[("client", "Client"), ("category", "Category")], db_index=True, max_length=20
            ),
        ),
        migrations.AddConstraint(
            model_name="master",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["client", "category"])), name="master_type_valid"
            ),
        ),
    ]
