# Generated by Django 6.0.4 on 2026-04-19 05:25
#
# Schema + data migration:
#   1. Add the new ``orgs`` ManyToManyField.
#   2. Seed it from the legacy ``org`` FK so existing clients /
#      categories keep working without an ops re-tag step.
# The reverse migration drops the M2M — the legacy ``org`` FK is left
# intact so no data is lost if we need to roll back.

from django.db import migrations, models


def copy_org_to_orgs(apps, schema_editor):
    Master = apps.get_model("masters", "Master")
    # Only rows that already have a legacy org set need seeding; rows
    # created after this migration runs write straight to ``orgs``.
    through = Master.orgs.through
    rows = [through(master_id=m.pk, org_id=m.org_id) for m in Master.objects.filter(org__isnull=False)]
    # ``bulk_create(ignore_conflicts=True)`` keeps the migration idempotent
    # — re-running on an already-migrated DB becomes a no-op rather than
    # raising an IntegrityError.
    through.objects.bulk_create(rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    """Nothing to do — dropping the M2M table is handled by AddField's
    reverse. The legacy ``org`` FK is untouched."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0003_remove_master_master_type_valid_alter_master_type_and_more"),
        ("users", "0002_remove_user_attendance_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="master",
            name="orgs",
            field=models.ManyToManyField(blank=True, related_name="shared_masters", to="users.org"),
        ),
        migrations.RunPython(copy_org_to_orgs, noop_reverse),
    ]
