# Generated by Django 6.0.4 on 2026-04-21 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_master_orgs'),
        ('users', '0002_remove_user_attendance_access_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('meeting_date', models.DateField(db_index=True)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('meeting_type', models.CharField(choices=[('Review', 'Review'), ('Kickoff', 'Kickoff'), ('Escalation', 'Escalation'), ('Strategic', 'Strategic'), ('Ad-hoc', 'Ad-hoc')], default='Review', max_length=20)),
                ('mode', models.CharField(choices=[('In-person', 'In-person'), ('Video', 'Video'), ('Phone', 'Phone')], default='Video', max_length=20)),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('client_attendees', models.JSONField(blank=True, default=list)),
                ('agenda', models.TextField(blank=True, default='')),
                ('minutes', models.TextField(blank=True, default='')),
                ('next_meeting_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'type': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='masters.master')),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_client_meetings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_meetings', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_meetings', to='users.org')),
                ('our_attendees', models.ManyToManyField(blank=True, related_name='attended_client_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client meeting',
                'verbose_name_plural': 'client meetings',
                'ordering': ['-meeting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientMeetingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to='client_meetings/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='masters.clientmeeting')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_client_meeting_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client meeting attachment',
                'verbose_name_plural': 'client meeting attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Achieved', 'Achieved'), ('At Risk', 'At Risk'), ('Cancelled', 'Cancelled')], db_index=True, default='Not Started', max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('progress_notes', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'type': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmaps', to='masters.master')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_roadmaps', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_roadmaps', to='users.org')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_client_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client roadmap item',
                'verbose_name_plural': 'client roadmap items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientActionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('responsibility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_client_action_points', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_points', to='masters.clientmeeting')),
                ('roadmap_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_action_points', to='masters.clientroadmap')),
            ],
            options={
                'verbose_name': 'client action point',
                'verbose_name_plural': 'client action points',
                'ordering': ['target_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientmeeting',
            index=models.Index(fields=['client', 'meeting_date'], name='cm_meeting_client_date_idx'),
        ),
        migrations.AddIndex(
            model_name='clientroadmap',
            index=models.Index(fields=['client', 'status'], name='cm_roadmap_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clientroadmap',
            index=models.Index(fields=['target_date'], name='cm_roadmap_target_idx'),
        ),
        migrations.AddIndex(
            model_name='clientactionpoint',
            index=models.Index(fields=['meeting', 'status'], name='cm_action_meeting_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clientactionpoint',
            index=models.Index(fields=['target_date'], name='cm_action_target_idx'),
        ),
    ]
