# Generated by Django 6.0.4 on 2026-04-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0005_client_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientroadmap",
            name="expected_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
