# Generated by Django 6.0.4 on 2026-04-27 02:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_client_roadmap_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientActionPointAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to='client_action_points/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('action_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='masters.clientactionpoint')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_client_action_point_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client action point attachment',
                'verbose_name_plural': 'client action point attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
