# Generated by Django 6.0.4 on 2026-04-27 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_clientactionpointattachment'),
        ('users', '0003_orgmembership_leads_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('visit_date', models.DateField(db_index=True)),
                ('current_status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Draft', max_length=20)),
                ('report_sent_date', models.DateField(blank=True, null=True)),
                ('voice_note_sent', models.BooleanField(default=False)),
                ('voice_note_summary', models.TextField(blank=True, default='')),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_client_visits', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'type': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='masters.master')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_visits', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_visits', to='users.org')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_client_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client visit',
                'verbose_name_plural': 'client visits',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('key_points', models.TextField(blank=True, default='')),
                ('observation_attachment', models.FileField(blank=True, null=True, upload_to='client_visits/%Y/%m/')),
                ('attachment_filename', models.CharField(blank=True, default='', max_length=255)),
                ('attachment_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_comment', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_visit_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_visit_reports', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='masters.clientvisit')),
            ],
            options={
                'verbose_name': 'visit report',
                'verbose_name_plural': 'visit reports',
                'ordering': ['visit', 'revision_number'],
            },
        ),
        migrations.CreateModel(
            name='VisitReportAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted'), ('sent_to_client', 'Sent to client'), ('voice_note_marked', 'Voice note marked')], max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='masters.visitreport')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='masters.clientvisit')),
            ],
            options={
                'verbose_name': 'visit report audit event',
                'verbose_name_plural': 'visit report audit events',
                'ordering': ['visit', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientvisit',
            index=models.Index(fields=['client', '-visit_date'], name='cv_client_date_idx'),
        ),
        migrations.AddIndex(
            model_name='clientvisit',
            index=models.Index(fields=['org', 'report_sent_date', 'visit_date'], name='cv_overdue_idx'),
        ),
        migrations.AddIndex(
            model_name='clientvisit',
            index=models.Index(fields=['org', 'current_status'], name='cv_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='visitreport',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='visit_report_revision_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='visitreport',
            unique_together={('visit', 'revision_number')},
        ),
    ]
