# Generated by Django 6.0.4 on 2026-04-29 00:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_visit_audit_event_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitreport',
            name='attachment_filename',
        ),
        migrations.RemoveField(
            model_name='visitreport',
            name='attachment_size_bytes',
        ),
        migrations.RemoveField(
            model_name='visitreport',
            name='observation_attachment',
        ),
        migrations.CreateModel(
            name='VisitReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to='client_visits/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='masters.visitreport')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_visit_report_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'visit report attachment',
                'verbose_name_plural': 'visit report attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
