# Generated by Django 6.0.4 on 2026-05-10 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_master_recurrence_target_day'),
        ('users', '0005_orgmembership_exclude_op_standup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='master',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='master',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('type', 'name', 'org'), name='master_unique_main'),
        ),
        migrations.AddConstraint(
            model_name='master',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('type', 'name', 'org', 'parent'), name='master_unique_sub'),
        ),
    ]
