# Generated by Django 5.2.13 on 2026-05-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0016_master_unique_per_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="master",
            name="recurrence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Onetime", "One-time"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("Quarterly", "Quarterly"),
                    ("Halfyearly", "Half-yearly"),
                    ("Yearly", "Yearly"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
