# Generated by Django 6.0.4 on 2026-07-06 12:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0018_master_designation_type'),
        ('users', '0009_orgmembership_budget_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('financial_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('line_type', models.CharField(choices=[('budget', 'Budget'), ('actual', 'Actual')], max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'type': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_line_items', to='masters.master')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_line_items', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_line_items', to='users.org')),
            ],
            options={
                'verbose_name': 'budget line item',
                'verbose_name_plural': 'budget line items',
                'ordering': ['client__name', 'financial_year', 'month', 'line_type'],
                'indexes': [models.Index(fields=['client', 'financial_year'], name='budget_client_fy_idx')],
            },
        ),
    ]
