# Generated by Django 6.0.4 on 2026-04-29 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0011_visit_report_multi_attachment'),
        ('users', '0003_orgmembership_leads_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('entry_date', models.DateField(db_index=True)),
                ('area', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('takeaway', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'type': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaizens', to='masters.master')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaizens', to='users.org')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_kaizens', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kaizens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'kaizen entry',
                'verbose_name_plural': 'kaizen entries',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['status', '-entry_date'], name='kaizen_status_date_idx')],
            },
        ),
    ]
