# Generated by Django 6.0.4 on 2026-04-17 03:30

import uuid

import django.core.validators
from django.db import migrations, models

import core.filestore.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InvoiceEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("invoice_month", models.DateField(db_index=True)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Uploaded", "Uploaded"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, default="", max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to=core.filestore.validators.invoice_upload_to),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "invoice entry",
                "verbose_name_plural": "invoice entries",
                "ordering": ["invoice_month", "invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoicePlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "serial_no",
                    models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
                ),
                ("job_description", models.TextField()),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Half-yearly", "Half-yearly"),
                            ("Yearly", "Yearly"),
                        ],
                        default="Monthly",
                        max_length=20,
                    ),
                ),
                ("start_month", models.DateField()),
                ("end_month", models.DateField()),
                (
                    "invoice_day",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                "verbose_name": "invoice plan",
                "verbose_name_plural": "invoice plans",
                "ordering": ["start_month"],
            },
        ),
    ]
