# Generated by Django 5.2.13 on 2026-05-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_invoicecategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceentry",
            name="project_status",
            field=models.CharField(
                choices=[("Confirmed", "Confirmed"), ("Projected", "Projected")],
                db_index=True,
                default="Projected",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoiceplan",
            name="project_status",
            field=models.CharField(
                choices=[("Confirmed", "Confirmed"), ("Projected", "Projected")],
                db_index=True,
                default="Projected",
                max_length=20,
            ),
        ),
    ]
