# Generated by Django 6.0.4 on 2026-04-17 03:30

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("masters", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("date", models.DateField(db_index=True)),
                ("task_description", models.TextField()),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("24")),
                        ],
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Top Priority", "Top Priority"),
                            ("Priority", "Priority"),
                            ("Normal", "Normal"),
                            ("Not Urgent", "Not Urgent"),
                        ],
                        default="Normal",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "client"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_worklogs",
                        to="masters.master",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_logs",
                        to="users.org",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "work log",
                "verbose_name_plural": "work logs",
                "ordering": ["sort_order", "-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("date", models.DateField(blank=True, db_index=True, null=True)),
                ("task_description", models.TextField()),
                (
                    "planned_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("24")),
                        ],
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "client"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_workplans",
                        to="masters.master",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_work_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_plans",
                        to="users.org",
                    ),
                ),
            ],
            options={
                "verbose_name": "work plan",
                "verbose_name_plural": "work plans",
                "ordering": ["date"],
            },
        ),
    ]
