# Generated by Django 6.0.4 on 2026-04-18 16:08

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worklog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklog",
            name="hours_worked",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("24")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="workplan",
            name="planned_hours",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("24")),
                ],
            ),
        ),
    ]
