# Generated by Django 6.0.4 on 2026-04-17 03:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "serial_no",
                    models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
                ),
                ("contact_person", models.CharField(blank=True, default="", max_length=150)),
                ("contact_email", models.EmailField(blank=True, default="", max_length=254)),
                ("contact_phone", models.CharField(blank=True, default="", max_length=30)),
                ("lead_source", models.CharField(blank=True, default="", max_length=100)),
                ("reference_from", models.CharField(blank=True, default="", max_length=255)),
                (
                    "priority",
                    models.CharField(
                        choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                        default="Medium",
                        max_length=20,
                    ),
                ),
                ("estimated_value", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("action_taken", models.TextField(blank=True)),
                ("next_step", models.TextField(blank=True)),
                ("next_step_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "lead",
                "verbose_name_plural": "leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "lead history entry",
                "verbose_name_plural": "lead history",
                "db_table": "lead_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(default="#64748b", max_length=20)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "lead status",
                "verbose_name_plural": "lead statuses",
                "ordering": ["sort_order"],
            },
        ),
    ]
