# Generated by Django 6.0.4 on 2026-04-17 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadstatus",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_statuses",
                to="users.org",
            ),
        ),
        migrations.AlterField(
            model_name="leadstatus",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="leadstatus",
            constraint=models.UniqueConstraint(fields=("org", "name"), name="unique_lead_status_name_per_org"),
        ),
    ]
