# Generated by Django 6.0.4 on 2026-04-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_leadstatus_org_alter_leadstatus_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="client_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
