# Generated by Django 6.0.4 on 2026-07-05 10:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("masters", "0018_master_designation_type"),
        ("users", "0008_orgmembership_costing_access"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostingEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("hr_day", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("days_working", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "client"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costing_entries_as_client",
                        to="masters.master",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costing_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "designation"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costing_entries_as_designation",
                        to="masters.master",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costing_entries",
                        to="users.org",
                    ),
                ),
            ],
            options={
                "verbose_name": "costing entry",
                "verbose_name_plural": "costing entries",
                "ordering": ["client__name", "designation__name"],
            },
        ),
    ]
