# Generated by Django 6.0.4 on 2026-07-06 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costing", "0001_initial"),
        ("employees", "0003_employee_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="costingentry",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="costing_entries",
                to="employees.employee",
            ),
        ),
    ]
