# Generated by Django 6.0.4 on 2026-07-14 14:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_costingentry_employee'),
        ('employees', '0003_employee_designation'),
        ('users', '0009_orgmembership_budget_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSeatCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_cost', to='employees.employee')),
            ],
            options={
                'verbose_name': 'employee seat cost',
                'verbose_name_plural': 'employee seat costs',
            },
        ),
        migrations.CreateModel(
            name='SeatCostSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_cost_setting', to='users.org')),
            ],
            options={
                'verbose_name': 'seat cost setting',
                'verbose_name_plural': 'seat cost settings',
            },
        ),
    ]
