# Generated by Django 6.0.4 on 2026-04-17 03:30

import uuid

import django.core.validators
from django.db import migrations, models

import core.filestore.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("employee_name", models.CharField(db_index=True, max_length=150)),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                        default="Male",
                        max_length=10,
                    ),
                ),
                ("blood_group", models.CharField(blank=True, default="", max_length=5)),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                        ],
                        default="Single",
                        max_length=20,
                    ),
                ),
                ("father_name", models.CharField(blank=True, default="", max_length=150)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("alt_phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("permanent_address", models.TextField(blank=True)),
                ("current_address", models.TextField(blank=True)),
                (
                    "aadhar_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Aadhaar must be exactly 12 digits.", regex="^\\d{12}$"
                            )
                        ],
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="PAN must be in the format ABCDE1234F (5 letters, 4 digits, 1 letter).",
                                regex="^[A-Z]{5}[0-9]{4}[A-Z]$",
                            )
                        ],
                    ),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=150)),
                ("bank_account", models.CharField(blank=True, default="", max_length=30)),
                (
                    "ifsc_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="IFSC must be 4 letters, a 0, then 6 alphanumerics (e.g. HDFC0001234).",
                                regex="^[A-Z]{4}0[A-Z0-9]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "address_proof",
                    models.FileField(
                        blank=True, null=True, upload_to=core.filestore.validators.employee_address_proof_upload_to
                    ),
                ),
                ("emergency_contact_name", models.CharField(blank=True, default="", max_length=150)),
                ("emergency_contact_phone", models.CharField(blank=True, default="", max_length=20)),
                ("emergency_contact_relation", models.CharField(blank=True, default="", max_length=50)),
                ("reference_name", models.CharField(blank=True, default="", max_length=150)),
                ("reference_contact", models.CharField(blank=True, default="", max_length=20)),
                ("reference_relation", models.CharField(blank=True, default="", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive"), ("Resigned", "Resigned")],
                        db_index=True,
                        default="Active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "employee",
                "verbose_name_plural": "employees",
                "ordering": ["employee_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("designation", models.CharField(blank=True, default="", max_length=150)),
                ("department", models.CharField(blank=True, default="", max_length=150)),
                ("fixed_salary", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("basic_salary", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("hra", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("da", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("other_allowances", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("pf_number", models.CharField(blank=True, default="", max_length=30)),
                ("esi_number", models.CharField(blank=True, default="", max_length=30)),
                ("uan_number", models.CharField(blank=True, default="", max_length=30)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "employee salary",
                "verbose_name_plural": "employee salaries",
                "ordering": ["-effective_from"],
            },
        ),
    ]
