# Generated by Django 6.0.4 on 2026-04-17 03:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("masters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("changed_by_name", models.CharField(blank=True, default="", max_length=150)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("changes", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "task log",
                "verbose_name_plural": "task logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "serial_no",
                    models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("today_task", "Today Task"),
                            ("tomorrow", "Tomorrow"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("completed_delay", "Completed Delay"),
                            ("overdue", "Overdue"),
                            ("future_goal", "Future Task/Goals"),
                            ("tbc", "TBC"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("target_date", models.DateField(blank=True, db_index=True, null=True)),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("onetime", "One-time"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("halfyearly", "Half-yearly"),
                            ("yearly", "Yearly"),
                        ],
                        default="onetime",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "category"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category_tasks",
                        to="masters.master",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "client"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_tasks",
                        to="masters.master",
                    ),
                ),
            ],
            options={
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
                "ordering": ["target_date", "created_at"],
            },
        ),
    ]
