# Generated by Django 5.2.13 on 2026-05-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='engagement_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='engagement_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
