# Generated by Django 5.2.13 on 2026-05-10 06:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_tasksubcategoryplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasksubcategoryplan",
            name="uid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
