# Generated by Django 6.0.4 on 2026-04-23 14:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.filestore.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("masters", "0007_client_roadmap_start_date"),
        ("users", "0002_remove_user_attendance_access_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConveyanceEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("date", models.DateField(db_index=True)),
                ("reason", models.TextField(max_length=2000)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("claimable", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=500)),
                (
                    "client",
                    models.ForeignKey(
                        limit_choices_to={"type": "client"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_conveyance_entries",
                        to="masters.master",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conveyance_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conveyance_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conveyance_entries",
                        to="users.org",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conveyance_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "conveyance entry",
                "verbose_name_plural": "conveyance entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConveyanceAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("file", models.FileField(upload_to=core.filestore.validators.conveyance_attachment_upload_to)),
                ("label", models.CharField(blank=True, max_length=100)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conveyance_attachment_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="conveyance.conveyanceentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "conveyance attachment",
                "verbose_name_plural": "conveyance attachments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conveyanceentry",
            index=models.Index(fields=["org", "date"], name="conveyance__org_id_f99b9b_idx"),
        ),
        migrations.AddIndex(
            model_name="conveyanceentry",
            index=models.Index(fields=["org", "employee", "date"], name="conveyance__org_id_a156e3_idx"),
        ),
        migrations.AddIndex(
            model_name="conveyanceentry",
            index=models.Index(fields=["org", "client", "date"], name="conveyance__org_id_b05856_idx"),
        ),
        migrations.AddIndex(
            model_name="conveyanceentry",
            index=models.Index(fields=["org", "status"], name="conveyance__org_id_0787d8_idx"),
        ),
        migrations.AddIndex(
            model_name="conveyanceattachment",
            index=models.Index(fields=["entry"], name="conveyance__entry_i_e08a98_idx"),
        ),
    ]
