# Generated by Django 6.0.4 on 2026-04-17 03:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("date", models.DateField(db_index=True)),
                ("login_time", models.TimeField(blank=True, null=True)),
                ("logout_time", models.TimeField(blank=True, null=True)),
                (
                    "work_location",
                    models.CharField(
                        choices=[
                            ("Office", "Office"),
                            ("WFH", "WFH"),
                            ("Client Site", "Client Site"),
                            ("Field", "Field"),
                            ("Other", "Other"),
                        ],
                        default="Office",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Half Day", "Half Day"),
                            ("Leave", "Leave"),
                        ],
                        default="Present",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "attendance",
                "verbose_name_plural": "attendance",
                "ordering": ["-date", "user"],
            },
        ),
    ]
