# Generated by Django 6.0.4 on 2026-04-25 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('users', '0003_orgmembership_leads_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='approval_state',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_session',
            field=models.CharField(blank=True, choices=[('First Half', 'First Half'), ('Second Half', 'Second Half')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['approval_state', 'org'], name='attendance__approva_d24000_idx'),
        ),
    ]
