# Generated by Django 6.0.4 on 2026-04-17 03:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField(unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("National", "National"), ("Regional", "Regional"), ("Company", "Company")],
                        default="National",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "holiday",
                "verbose_name_plural": "holidays",
                "ordering": ["date"],
            },
        ),
    ]
